apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        value: "admin"
      - name: SECRET_PASSWORD  
        value: "123456"
  restartPolicy: Never