apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=          #(base64 olarak çevrilmiş şifre)
  password: MWYyZDFlMmU2N2Rm  #(base64 olarak çevrilmiş şifre)

  # echo -n 'admin' | base64 
